export const NEW_HOTEL_REQUEST = "NEW_HOTEL_REQUEST"
export const NEW_HOTEL_SUCCESS = "NEW_HOTEL_SUCCESS"
export const NEW_HOTEL_FAIL = "NEW_HOTEL_FAIL"
export const NEW_HOTEL_RESET = "NEW_HOTEL_RESET"

export const ALL_HOTELS_REQUEST = "ALL_HOTELS_REQUEST"
export const ALL_HOTELS_SUCCESS = "ALL_HOTELS_SUCCESS"
export const ALL_HOTELS_FAIL = "ALL_HOTELS_FAIL"

export const SELLER_HOTELS_REQUEST = "SELLER_HOTELS_REQUEST"
export const SELLER_HOTELS_SUCCESS = "SELLER_HOTELS_SUCCESS"
export const SELLER_HOTELS_FAIL = "SELLER_HOTELS_FAIL"

export const DELETE_HOTEL_REQUEST = "DELETE_HOTEL_REQUEST"
export const DELETE_HOTEL_SUCCESS = "DELETE_HOTEL_SUCCESS"
export const DELETE_HOTEL_FAIL = "DELETE_HOTEL_FAIL"

export const SINGLE_HOTEL_REQUEST = "SINGLE_HOTEL_REQUEST"
export const SINGLE_HOTEL_SUCCESS = "SINGLE_HOTEL_SUCCESS"
export const SINGLE_HOTEL_FAIL = "SINGLE_HOTEL_FAIL"

export const EDIT_HOTEL_REQUEST = "EDIT_HOTEL_REQUEST"
export const EDIT_HOTEL_SUCCESS = "EDIT_HOTEL_SUCCESS"
export const EDIT_HOTEL_FAIL = "EDIT_HOTEL_FAIL"
export const EDIT_HOTEL_RESET = "EDIT_HOTEL_RESET"