export const GET_SESSION_REQUEST = "GET_SESSION_REQUEST"
export const GET_SESSION_SUCCESS = "GET_SESSION_SUCCESS"
export const GET_SESSION_FAIL = "GET_SESSION_FAIL"

export const BUYER_PAYMENT_REQUEST = "BUYER_PAYMENT_REQUEST"
export const BUYER_PAYMENT_SUCCESS = "BUYER_PAYMENT_SUCCESS"
export const BUYER_PAYMENT_FAIL = "BUYER_PAYMENT_FAIL"
export const BUYER_PAYMENT_RESET = "BUYER_PAYMENT_RESET"

export const STRIPE_PAYMENT_REQUEST = "STRIPE_PAYMENT_REQUEST"
export const STRIPE_PAYMENT_SUCCESS = "STRIPE_PAYMENT_SUCCESS"
export const STRIPE_PAYMENT_FAIL = "STRIPE_PAYMENT_FAIL"

export const USER_ORDERS_REQUEST = "USER_ORDERS_REQUEST"
export const USER_ORDERS_SUCCESS = "USER_ORDERS_SUCCESS"
export const USER_ORDERS_FAIL = "USER_ORDERS_FAIL"

export const ALREADY_BOOKED_REQUEST = "ALREADY_BOOKED_REQUEST"
export const ALREADY_BOOKED_SUCCESS = "ALREADY_BOOKED_SUCCESS"
export const ALREADY_BOOKED_FAIL = "ALREADY_BOOKED_FAIL"