export const CREATE_CONNECT_ACCOUNT_REQUEST = 'CREATE_CONNECT_ACCOUNT_REQUEST'
export const CREATE_CONNECT_ACCOUNT_SUCCESS = 'CREATE_CONNECT_ACCOUNT_SUCCESS'
export const CREATE_CONNECT_ACCOUNT_FAIL = 'CREATE_CONNECT_ACCOUNT_FAIL'

export const CONTINUE_STRIPE_DETAILS = "CONTINUE_STRIPE_DETAILS"
export const COUNTRY_ENTITY = "COUNTRY_ENTITY"
export const STRIPE_PERSONAL_DETAILS = "STRIPE_PERSONAL_DETAILS"

export const ACCOUNT_STATUS_REQUEST = "ACCOUNT_STATUS_REQUEST"
export const ACCOUNT_STATUS_SUCCESS = "ACCOUNT_STATUS_SUCCESS"
export const ACCOUNT_STATUS_FAIL = "ACCOUNT_STATUS_FAIL"

export const ACCOUNT_BALANCE_REQUEST = "ACCOUNT_BALANCE_REQUEST"
export const ACCOUNT_BALANCE_SUCCESS = "ACCOUNT_BALANCE_SUCCESS"
export const ACCOUNT_BALANCE_FAIL = "ACCOUNT_BALANCE_FAIL"

export const PAYOUT_SETTING_REQUEST = "PAYOUT_SETTING_REQUEST"
export const PAYOUT_SETTING_SUCCESS = "PAYOUT_SETTING_SUCCESS"
export const PAYOUT_SETTING_FAIL = "PAYOUT_SETTING_FAIL"